### PR TITLE
Fixes #11: Adds call to ignoreAspectRatio() to the sharp function chain

### LINKED ISSUE #11: Images are being cropped when resized to generate hash
Images are being center cropped when resized before calculating hash. The sharp lib docs state that [`resize`](http://sharp.dimens.io/en/stable/api-resize/#resize) center crops images.

The solution is to call `ignoreAspectRatio` on the sharpjs resize function chain.

Cropping can cause a lot of issues when perceptual hashing.

### PR DESCRIPTION
**Pull request by cascornelissen**

### CODE REVIEW

**Review by lovell — APPROVED** [review]

**Comment by cascornelissen** [comment]
@lovell, any idea where the seg faults are coming from in CI?

**Comment by lovell** [comment]
The CI environment hasn't been touched for a couple of years so it's due a little maintenance. I'll take a look.

**Comment by lovell** [comment]
I pushed a commit https://github.com/mgmtio/dhash-image/commit/b154e6fccd264cf44277aeccef9c6db1645dd6c2 to a temp branch that updates Travis and a few of the dependencies (e.g. `istanbul` has been superseded by `nyc`) but it *still* segfaulted on Travis CI.

https://travis-ci.org/mgmtio/dhash-image/builds/419864270

Not sure what's going on here :confused:

**Comment by lovell** [comment]
This is probably related to https://github.com/lovell/sharp/issues/1344

I've created #13 to update the CI environment and workaround it.

**Comment by lovell** [comment]
Please can you rebase this PR against the `master` branch to pick up the CI environment changes.

**Comment by cascornelissen** [comment]
@lovell, done! ✌️

**Comment by lovell** [comment]
Great, thank you.

@jonathanong has the npm publishing power to get this released.

**Pull request merged**
